### PR TITLE
[FIX] Add Laravel 5.4 support

### PR DESCRIPTION
**Pull request by driesvints**
### Changes proposed in this pull request:

- Adds Laravel 5.4 support

This really doesn't breaks anything as far as I can tell. Or the tests are letting it pass :)
So I'm considering this a minor feature and sending it to the 1.2 branch.

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
L.5.4.2 was just released with a breaking change in the TokenRepositoryInterface.
I'm afraid we will need to support another version of it.

**Review by ilyabazhenov — APPROVED** [review]

**Comment by Cosmicist** [comment]
The [change](https://github.com/laravel/framework/commit/f292260554e1985f8dc1725489b3d5a07c552f7c) in Laravel seems to be to always delete all tokens for a user (calling protected method `TokenRepositoryInterface::deleteExisting(CanResetPassword $user)` from `delete()`, so basically, they ditched delete by token. `DoctrineTokenRepository` has this functionality as well (same method name, also protected).
I'll give it a go and see how it goes... :crossed_fingers: 

EDIT: seems that laravel did not yet release that breaking change on the [dedicated repo](https://github.com/illuminate/auth), there the latest tagged version is still 5.4.0

**Comment by driesvints** [comment]
@patrickbrouwers ok, I'll leave it to you then. Not to pressure you but any chance you can have a release out by next week? Would love to upgrade ^_^

If that's not possible, no problem of course.

**Comment by patrickbrouwers** [comment]
Not sure if I've time tbh, quite busy at the moment. If you can push a commit to this PR to fix compatibility that would be awesome.

**Comment by driesvints** [comment]
@patrickbrouwers I'll see what I can do. Can you perhaps tell me what you exactly expect me to do?

**Comment by patrickbrouwers** [comment]
Fixing the TokenRepositoryInterface implementation in the package.

**Comment by patrickbrouwers** [comment]
Commited it myself to 1.3

**Comment by driesvints** [comment]
Thank you so much for this! 

I see the build is still failing however. Seems like there's still something wrong with the token functionality?

**Comment by patrickbrouwers** [comment]
Yeah, it's because Taylor hasn't tagged auth package yet. It works with the
fullstack framework.

**Pull request closed without merging**
