### PR TITLE
[FIX] PaginateFromParams::paginateAll needs an int $page, not a string

### PR DESCRIPTION
**Pull request by guiwoda**
### Changes proposed in this pull request:
- Fixes https://github.com/laravel-doctrine/orm/issues/218 by changing default to int(1) and changing docblock

### CODE REVIEW

**Comment by maxbrokman** [comment]
I know you're only doing this because you're jealous I have more contributions than you.

**Comment by patrickbrouwers** [comment]
I'm searching so hard for a reason to decline this 🙊

**Comment by guiwoda** [comment]
hahahaha you got me!

**Comment by guiwoda** [comment]
I think I'll keep the branch tho. I may need it again in the future.

**Pull request merged**
