### PR TITLE
[FIX] doctrine/persistence upgrade issues

### PR DESCRIPTION
**Pull request by bounoable**
`doctrine/persistence 1.3` deprecated/changed namespaces and broke service container bindings.
see https://github.com/laravel-doctrine/orm/issues/414

### CODE REVIEW

**Comment by dpslwk** [comment]
need to remove 
```
    "conflict": {
        "doctrine/persistence": ">=1.3@dev"
    },
```

from composer.json

**Comment by xtrasmal** [comment]
@eigan If the PR #422 solves this issue for those using laravel-doctrine:1.5, could this be merged as soon as possible?

**Comment by eigan** [comment]
Current release of 1.5 should have the fix provided in the comment above. Only downside is you won't get the latest version of doctrine/persistence. Is this causing any issue for you?

**Comment by xtrasmal** [comment]
@eigan I wasn't aware. I've just updated our codebases and it seems to be working as before. Good busy, thanks.

**Comment by eigan** [comment]
Would be nice if someone could test these changes in a test-suite. 

Update your composer.json to use `"laravel-doctrine/orm": "1.5.x-dev"` and try it out. Thanks :)

(We are using 1.4 at work, so not able to test it. Though I hope the tests in this repo is sufficient..).

**Comment by dpslwk** [comment]
its all working for me

**Comment by eigan** [comment]
Thank you @bounoable and @dpslwk! Released with 1.5.4 now.

**Pull request merged**
