### PR TITLE
[FIX] doctrine generate entities command

### PR DESCRIPTION
**Pull request by amitailanciano**
### Changes proposed in this pull request:
- change default path to current working directory and use argument path if provided
- use same defaults as original doctrine command

### CODE REVIEW

**Comment by amitailanciano** [comment]
maybe default entity path could be set in config and use that instead of current working directory if not supplied

**Comment by patrickbrouwers** [comment]
Good spot, forgot to put that back to dest-path.

But why `'.'` when no dest-path is given?

**Comment by patrickbrouwers** [comment]
Going to close this one in favour of https://github.com/laravel-doctrine/orm/pull/133

**Comment by amitailanciano** [comment]
that's fine, but can you also include the parameter defaults from the original command?

This commit: https://github.com/laravel-doctrine/orm/pull/135/commits/96ed3e16f4269b23f9ddded98736499ab2b874a3

If you'd like to implement that differently that's ok, I just think it's really helpful for those to be the defaults

**Comment by patrickbrouwers** [comment]
It already has those defaults:

if(null) == if(false)

**Comment by amitailanciano** [comment]
I was being explicit with those two -- you are right that they are not needed, but there are also two conditions where `true` is the default if `null`

**Comment by amitailanciano** [comment]
See https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Console/Command/GenerateEntitiesCommand.php for the original command defaults

**Comment by patrickbrouwers** [comment]
Ah didn't spot the two true's. If you can make a new PR with that commit, would be nice, thanks.

**Comment by amitailanciano** [comment]
Here you go https://github.com/laravel-doctrine/orm/pull/138

**Pull request closed without merging**
