### PR TITLE
Add native support for Carbon instead of DateTime

### PR DESCRIPTION
**Pull request by CaporalDead**
Based on http://blog.damirmiladinov.com/using-carbon-php-with-laravel-doctrine.html, support for Carbon instance instead of DateTime instance.

### CODE REVIEW

**Comment by josenicomaia** [comment]
It's a great job, but I am not sure if it is necessary the modification in the `DoctrineServiceProvider`.

You can simple overide the doctrine type putting on the custom_types:

``` php
    'custom_types'              => [
        'json' => LaravelDoctrine\ORM\Types\Json::class,
        'datetime' => \LaravelDoctrine\ORM\Types\Carbon::class
    ]
```

`CustomTypeManager` already does what `registerOverridedTypes()` is doing.

+1 for TypeNotFound, Carbon and Tests :D

**Comment by CaporalDead** [comment]
Hmmm, yeah you're right ><, didn't check what addCustomTypes was supposed to do. A quick patch is on its  way :).

**Comment by patrickbrouwers** [comment]
No changes are required for this.

Like @josenicomaia stated, you can use `custom_types` for this.

The Carbon implementation is already provided by DoctrineExtensions: http://www.laraveldoctrine.org/docs/1.0/extensions/custom-functions
and also provides the other Carbon types like CarbonTime

`"beberlei/DoctrineExtensions": "^1.0"`

**Comment by CaporalDead** [comment]
Hmmm, back to basics : RTFM... :)

**Comment by patrickbrouwers** [comment]
I wish Github issues had that feature, on first issue submit, you have to confirm you read the documentation haha :p ;)

**Comment by CaporalDead** [comment]
:+1:

**Comment by josenicomaia** [comment]
Maybe it is the case that we can improve your documentation too :D

**Pull request closed without merging**
