### PR TITLE
[FIX/FEATURE] Don't extend the auth manager unless it's been bound

### LINKED ISSUE #302: [PROPOSAL] Don't extend the auth manager unless it's been bound
### Package version, Laravel version

1.4, 5.5

### Expected behaviour

https://github.com/laravel-doctrine/orm/blob/1.4/src/DoctrineServiceProvider.php#L251 should check if the auth manager has been bound before extending it.

### Actual behaviour

It doesn't check, so the auth manager is built from the container whether we need it or not

I've been trying to optimize an application and despite my best efforts this service provider is still the heaviest to register/boot. We don't use the Auth manager at all so the work done here is of no use to us, thus it would be great if it was optional, like `extendNotificationChannel`.

I can make a PR if this has a chance of getting accepted.

### PR DESCRIPTION
**Pull request by Jalle19**
Closes #302

### Changes proposed in this pull request:
- Only extend the auth manager if it has been bound

### CODE REVIEW

**Comment by Jalle19** [comment]
Will have to double-check whether this has the desired effect.

**Comment by Jalle19** [comment]
Just verified with the debugger, seems to work as intended. The auth manager only gets extended if `$app->register(\Illuminate\Auth\AuthServiceProvider::class);` has been made during bootstrapping.

**Comment by Jalle19** [comment]
Test failure is unrelated (fixed in https://github.com/laravel-doctrine/orm/pull/309)

**Comment by Jalle19** [comment]
@patrickbrouwers any chance you could have a look at my PRs here and in the laravel-doctrine/migrations repository?

**Comment by Jalle19** [comment]
Who should I ping to get this moving?

**Comment by eigan** [comment]
You could try on Slack.

**Pull request merged**
