### PR TITLE
Updating config as Laravel way

### PR DESCRIPTION
**Pull request by Amrit01**
Registering service providers and facade alias as Laravel does.

Sorry if i do something wrong.I am new to github and pull requests

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Hey, I can't merge this, because this would add orm code into the docs. I'm not sure how you managed that, haha :D

Did you merge laravel-doctrine/orm into laravel-doctrine/docs ?

**Comment by josenicomaia** [comment]
I didn't realize.
I guess that there is a README.md in root folder

**Comment by patrickbrouwers** [comment]
I'm sorry I misread the PR. But I still can't really merge it because of the unnecessary merge commit.

If you could first sync your ORM repo and than make the changes, it will be okay. Thanks.

**Comment by Amrit01** [comment]
I am very new to github, how should i do it is there any tutorial u can refer

**Comment by patrickbrouwers** [comment]
The easiest way would be to remove your fork and fork it again :)

**Comment by Amrit01** [comment]
Okay i will try that . How to sync my repo with your repo? will it be done automatically ?

**Comment by patrickbrouwers** [comment]
If you make a new fork after you have deleted it, you will automatically get the latest code.

**Comment by josenicomaia** [comment]
Did you cloned using git or https?

If you are using git, check if there is a laravel-doctrine or upstream remote.
To check it, you can execute:
git remote -v

**Pull request closed without merging**
