### PR TITLE
[FIX] use correct ManagerRegistry interface & pass tests

### PR DESCRIPTION
**Pull request by bounoable**
New version of doctrine/persistence broke the SubstituteBindings middleware and also the tests for the ServiceProvider. PR fixes the used ManagerRegistry interface.

### CODE REVIEW

**Comment by dpslwk** [comment]
Pretty sure this change should also include `"doctrine/persistence": "^1.3"` in composer `require` 
since this change would no longer work with persistence 1.2

**Comment by eigan** [comment]
I am on vacation now, so I will not be able to review these changes. We should figure out if 1.4 is affected too. 

I am back on wednesday and will set aside some time then, unless some other maintainer got the time of course :)

**Comment by bounoable** [comment]
@eigan 
So I just had a rough night because there is at least one other problem caused by some Laravel update after 6.0 and I couldn't figure out what exactly is causing it, but somehow LaravelDoctrine's request validation is broken, too. Laravels built in 'exists' => 'entity,id' isn't overwritten, resulting in an Exception, because the entities cannot be instantiated. I'll see if I can figure it out until you're back from vacation :)

**Comment by bounoable** [comment]
Found the commit :man_facepalming:
https://github.com/laravel/framework/commit/5728c66b0a444086a34b5bc1fe5ac866251fab90#diff-bfe2e79d87a34030e1cd049713a78cdaL818

Laravel assumes that the provided string is a Model class and just instantiates it. Will create a PR to that within laravel/framework.

**Comment by thrashzone13** [comment]
Is it solved yet?

**Comment by dpslwk** [comment]
looks like the validation issue fix was merged https://github.com/laravel/framework/pull/30840 and released in larval 6.8.0

**Comment by thrashzone13** [comment]
For those who are stuck like me just add  "doctrine/persistence": "1.2.0" to composer.It will downgrade doctrine persistence and solves the problem for now but don't forget to remove it after fixes

**Comment by eigan** [comment]
Note: I am back from vacation, but was simply too much stuff going on at work today. So im exhausted. Will try again tomorrow.

**Comment by eigan** [comment]
@bounoable Could you download the diff from styleci and apply the changes with `git apply file.diff`?. 

Then commit and rebase on top of 1.4?

**Comment by eigan** [comment]
I have released fix for 1.4 and 1.5. Still want this PR in for 1.5 though :-)

Could you do the following:
1. Rebase on top of 1.5
2. Squash commits.
3. Update the commit message with reasoning. Like what you have in your PR description
> New version of doctrine/persistence broke the SubstituteBindings middleware
>
> doctrine/persistence 1.3 changed the namespace for ManagerRegistry.

**Comment by bounoable** [comment]
closing for https://github.com/laravel-doctrine/orm/pull/420 :)

**Pull request closed without merging**
