### PR TITLE
Updating config as Laravel does

### PR DESCRIPTION
**Pull request by Amrit01**
Registering service providers and facade alias as Laravel does.

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Great! Good job :) And thanks for the contribution :)

**Comment by Amrit01** [comment]
My pleasure, in my forked version it says This branch is 1 commit behind laravel-doctrine:master what should I do ?

**Comment by patrickbrouwers** [comment]
You can do two things:
- Remove your fork again
- Sync the branches ( = clicking pull request)

**Comment by Amrit01** [comment]
Clicked on pull request .
it says ,There isn’t anything to compare

**Comment by patrickbrouwers** [comment]
Okay, odd.

**Comment by Amrit01** [comment]
I am going crazy with it..

**Comment by patrickbrouwers** [comment]
If you have a laracast subscription: https://laracasts.com/series/git-me-some-version-control

**Comment by Amrit01** [comment]
Sorry i don't have, it is hard to get credit card in my country

**Comment by patrickbrouwers** [comment]
https://help.github.com/articles/good-resources-for-learning-git-and-github/

**Comment by Amrit01** [comment]
thanks on it

**Comment by josenicomaia** [comment]
@Amrit01 Came with us to Slack. I can help you at GIT.
http://slack.laraveldoctrine.org/

**Comment by Amrit01** [comment]
ok

**Pull request merged**
