### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/orm.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "laravel-doctrine/orm": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by 77web** [comment]
Now that Laravel11 has released, this PR should be proceeded. (I'll try today :)

**Comment by 77web** [comment]
I tried this branch for my product along with laravel-doctrine/extensions https://github.com/laravel-doctrine/extensions/pull/66 and laravel-doctrine/migrations https://github.com/laravel-doctrine/migrations/pull/135 , it worked perfectly and all tests in my product passed successfully.
No update for config was needed, just run "composer update".

**Comment by DK-Mino** [comment]
Is there any update on this ?

**Comment by 77web** [comment]
We should fix builds first, maybe?

**Comment by 77web** [comment]
I almost fixed builds in #575.
Only 1 phpstan failure left, but I have no idea how to fix it :(

---

update: I've fixed the problem in #575 :tada:

**Comment by eigan** [comment]
Replaced by #575

**Pull request closed without merging**
