### PR TITLE
LogFormatter convertParams fix for passing nested array as params

### PR DESCRIPTION
**Pull request by 0x9be00ff1**
add support to doctrine json_array type

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Can you back this up with unit tests, please :)

**Comment by 0x9be00ff1** [comment]
I'll add the tests.
Is it proper to covert params using laravel e helper? it looks little unfriendly when using a FileLogger.

**Comment by patrickbrouwers** [comment]
Can you post file logger example, I didn't notice anything strange when I tested it

**Comment by 0x9be00ff1** [comment]
`SELECT * FROM table WHERE column = "{&quot;key1&quot;:&quot;value1&quot;,&quot;key2&quot;:{&quot;key21&quot;:&quot;value22&quot;}}`

is it what you want? :)

**Comment by patrickbrouwers** [comment]
hm perhaps the arrays should be escaped then.

**Comment by 0x9be00ff1** [comment]
These sqls are just for logging, unescaped strings looks much better, shall we just leave it alone?
or we need something like PDO::quote().

**Comment by patrickbrouwers** [comment]
Better safe than sorry

``` php
} else {
    $param = e($param);
}

return (string) $param;
```

**Comment by patrickbrouwers** [comment]
Can you make the change I suggested?

**Comment by patrickbrouwers** [comment]
:+1:

**Comment by 0x9be00ff1** [comment]
@patrickbrouwers  Can we tag a new release with this pr?

**Comment by patrickbrouwers** [comment]
Sorry, completely forgot about this. Yes, will do.

**Pull request merged**
