### PR TITLE
[FIX] Mapping convertion using database

### PR DESCRIPTION
**Pull request by R3VoLuT1OneR**
Hey I just found small "syntax" errors in "doctrine:convert:mapping" command.

Please merge the fix.

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Please re-add the `=` to `--from-database`

**Comment by R3VoLuT1OneR** [comment]
@patrickbrouwers If remove it, code `$this->option('from-database') === true` never be true.

`--from-database` - Without `=` parsed as boolean ( set or not set ) and `--form-database=` parsed always as string. Because here we have option set/not set and no value required I think should be used `--form-data`.

**Comment by R3VoLuT1OneR** [comment]
@patrickbrouwers And in original doctrine command it is `--from-database` without `=`

**Comment by patrickbrouwers** [comment]
Ah I was in the impression you could pass the database name to that option.

**Pull request merged**
