### PR TITLE
[FEATURE] Add support for Laravel 7.x

### PR DESCRIPTION
**Pull request by barryo**
All tests pass and `DoctrineTokenRepository` updated with tests.

Not tested on an application yet but changes are minor and should be
fine. Would be useful if someone else could test as I have no
production apps on Laravel 7 just yet.

No 1.6 or master branch to PR against.

### CODE REVIEW

**Comment by eigan** [comment]
Great work @barryo! :)

**Comment by eigan** [comment]
The following packages also needs to release new versions for L7 support.

I will try to finish up the releases at the end of the week.

- [x] https://github.com/laravel-doctrine/migrations
- [x] https://github.com/laravel-doctrine/extensions
- [x] https://github.com/laravel-doctrine/acl

**Comment by barryo** [comment]
Thanks for merging @eigan - I have open PRs for extensions and acl which should pass tests now that v1.6 is released. I missed migrations - if you don't get to it in the next couple days, I'll try.

**Comment by eigan** [comment]
We need to upgrade to doctrine/migrations 2.0 for composer to be happy. Will take a look tomorrow.

**Comment by eigan** [comment]
I did try to upgrade to migrations 2.0, but it went pretty bad. Lots of refactoring, so need to spend some time to get it right, which I currently do not have sadly.

**Pull request merged**
