### PR TITLE
[FEATURE] Add attributes metadata support [Issue #494]

### PR DESCRIPTION
**Pull request by dretsa**
### Changes proposed in this pull request:
- Add new attributes metadata support

### CODE REVIEW

**Comment by dretsa** [comment]
The only thing that needs to be checked is that this commit doesn't throw errors because `AttributeDriver` was added in `doctrine/orm:2.9`, but composer.json specifies `^2.6|^2.7|^2.8`, which AFAIK would behave the same as `^2.6`.

**Comment by eigan** [comment]
Thanks @colorninja 🙂 

I have vacation but will take a look at this when I get the time.

**Comment by eigan** [comment]
@colorninja Could you rebase on 1.5 and set target to 1.5? :)

**Comment by eigan** [comment]
Nevermind. I just cherry-picked you commit instead. Much easier. Thanks!

**Pull request closed without merging**
