### PR TITLE
 [FIX] laravel 5.8 update. composer and helpers fix

### PR DESCRIPTION
**Pull request by kaur58**
### Changes proposed in this pull request:
- composer json change to support laravel 5.8
- replaced deprecated array and string helper functions (https://laravel-news.com/laravel-5-8-deprecates-string-and-array-helpers)

### CODE REVIEW

**Comment by barryo** [comment]
For what it's worth, this PR works well for Laravel 5.8 on our project [inex/IXP-Manager](https://github.com/inex/IXP-Manager).

**Comment by volkanbektas** [comment]
When will this be merged?

**Comment by sojeda** [comment]
Awaiting

**Comment by byfoz** [comment]
@kaur58 Method `Illuminate\Events\Dispatcher::fire()` was deprecated in 5.4 and has been removed in Laravel 5.8. 

Line 281 and 287 in `DoctrineServiceProvider.php` need to use the `dispatch` method instead of `fire`, like so:
```
    /**
     * Boots the extension manager at the appropriate time depending on if the app
     * is running as Laravel HTTP, Lumen HTTP or in a console environment
     */
    protected function bootExtensionManager()
    {
        $manager = $this->app->make(ExtensionManager::class);

        if ($manager->needsBooting()) {
            $this->app['events']->dispatch('doctrine.extensions.booting');

            $this->app->make(ExtensionManager::class)->boot(
                $this->app['registry']
            );

            $this->app['events']->dispatch('doctrine.extensions.booted');
        }
    }
```

**Comment by kaur58** [comment]
Nice catch. replaced the fire method

**Comment by vv12131415** [comment]
Hi @kaur58 ! Thank you for the PR!

can you please make changes to 
https://github.com/laravel-doctrine/orm/blob/aa338bacb36ca6ff066345a6cd01d1cbc4ea33d9/src/Configuration/Cache/IlluminateCacheAdapter.php#L69-L73

since cache now is stored in seconds instead of minutes

also return the value ( instead of `return true` on line 73 remove it and put ` return $this->cache->put($id, $data, $lifeTimeMinutes);` and change the annotation of the file)


and we are ready to go!

**Comment by kaur58** [comment]
i changed it a little more. also change the forever part since that returns boolean now too

**Comment by jrgilman** [comment]
@vladyslavstartsev does this mean 1.4 branch is fully Laravel 5.8 compatible? If so, I will submit a PR to modify the README.

**Comment by vv12131415** [comment]
@jrgilman sorry for late response, yes it is Laravel 5.8 compatible right now

**Pull request merged**
