### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/laravel-doctrine/orm/pull/538/commits/00a7ebbcdd395879e668627581d43fa65dd7f7fd?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/orm.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "laravel-doctrine/orm": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by eigan** [comment]
Sadly, its not that easy. We need to do lots of stuff for dbal 3, which there was a PR for at some point.

**Comment by jasonmccreary** [comment]
Of course. This automation meant to help jump start the process. While it may be all that is needed in some cases, its definitely not designed with that intention.

**Comment by jurgenbosch** [comment]
Is anyone actively working on supporting Laravel 10?

**Comment by eigan** [comment]
No

**Comment by PrinsFrank** [comment]
For anyone following this thread: I created a PR to the 1.8 branch to add support for laravel 10 without the need for a DBAL upgrade in PR #555

**Pull request closed without merging**
