### PR TITLE
Add factory callbacks

### PR DESCRIPTION
**Pull request by dallincoons**
This PR makes an update to include factory callbacks, introduced in 5.6 https://laravel.com/docs/5.7/database-testing#factory-callbacks

### CODE REVIEW

**Comment by vv12131415** [comment]
@garret-gunter thanks for mentioning this.

Can we ask at main laravel repo to add Factory interface? So we can see all the methods that are not implemented in our code

**Comment by garret-gunter** [comment]
@vladyslavstartsev I make a proposal issue to add an interface.  Let's see what they think about the idea.
 https://github.com/laravel/ideas/issues/1682

**Comment by garret-gunter** [comment]
It doesn't look like there is any interest in an interface from upstream.  We should just merge this for now.

**Comment by vv12131415** [comment]
@garret-gunter OK, I've asked about this idea on Twitter and  Taylor is not against this. See https://twitter.com/IssecMura/status/1151237150752591872?s=19

**Comment by garret-gunter** [comment]
@vladyslavstartsev I made a pull request.
https://github.com/laravel/framework/pull/29207

**Pull request merged**
