### PR TITLE
[FIX] Hashing password-reset tokens before storing

### PR DESCRIPTION
**Pull request by rosamarsky**
[FIX] Fix for issue #506. Hashing password-reset tokens before storing.

### CODE REVIEW

**Comment by eigan** [comment]
As @dpslwk pointed out, this is invalidating all existing tokens. Though we never release a new major so cannot really see how else we can solve this...

**Comment by rosamarsky** [comment]
@eigan, maybe you can create a dev branch with all backward incompatible commits and tag it with git like `dev-master` and merge it someday with a new major version. 

BTW, I don't see a problem if this commit invalidates all tokens. You can just use the password recovery request again to get a new link with a new token.

**Comment by dpslwk** [comment]
I believe `src/Auth/Passwords/PasswordBrokerManager.php` also needs an update to pass the new constructor param

**Comment by dpslwk** [comment]
oh and looks like we should have also done this change 
https://github.com/laravel/framework/pull/13270/files

back around  v5.2.31 (2016-04-27), as the change to APP_KEY gen was introduced in v5.2.26 (2016-03-25)

**Comment by rosamarsky** [comment]
@dpslwk sorry, I forgot to add this file to the commit

**Comment by dpslwk** [comment]
> @dpslwk sorry, I forgot to add this file to the commit

no worries its why we have code review 😉

**Comment by eigan** [comment]
Thank you @rosamarsky and @dpslwk!


Going for a release announcement instead of bc. Sorry in advance for anyone getting angry users over this.

**Comment by dpslwk** [comment]
make some sense, I mean these a reset tokens they should only have a short lifetime anyway so effects should only be during a short transition period

**Pull request merged**
