### PR TITLE
[FEATURE]Update doctrine/orm to 2.6

### PR DESCRIPTION
**Pull request by sztyup**
### Changes proposed in this pull request:
- Use the recently relased 2.6 version of the doctrine ORM which has many improvements.

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
@sztyup how well did you test this in your own app/a test app? Does everything still work, no changes on doctrine side that break anything on our side?

**Comment by sztyup** [comment]
@patrickbrouwers I tested it on two of my own apps and as far as I can tell nothing breaks

**Comment by sztyup** [comment]
Here are the possible BC breaks from the update, the only important is the php7.1 requirement, which should to be documented here too.
EDIT: I realized its better than that, for users with 7.0 it sticks with orm 2.5 and for 7.1 it updates to 2.6
https://github.com/doctrine/doctrine2/releases/tag/v2.6.0

**Comment by xtrasmal** [comment]
Can we update?
I really like to use https://github.com/Ocramius/DoctrineBatchUtils which uses orm 2.6

**Comment by patrickbrouwers** [comment]
Thanks for the PR, installing with 2.6 should be possible now. Will indeed install 2.5 if you are using <7.1

**Pull request merged**
