### PR TITLE
Improved checking if framework is Lumen or not

### PR DESCRIPTION
**Pull request by Amrit01**

### CODE REVIEW

**Comment by ryan-senn** [comment]
If this pull-request gets accepted, don't forget to replicate it for the MigrationsServiceProvider and AclServiceProvider!

**Comment by patrickbrouwers** [comment]
Is ->version() available on the Application contract?

**Comment by Amrit01** [comment]
yes it is available

**Comment by patrickbrouwers** [comment]
Nice. Can you rebase your commits for me :)

**Comment by Amrit01** [comment]
Right not i am not in my laptop. will it be a problem to do it with 2 commit ?

**Comment by patrickbrouwers** [comment]
You can select the last to commits with `git rebase -i HEAD~2`

**Comment by Amrit01** [comment]
I don't know what am i doing with git .. learning to use it :)

**Comment by patrickbrouwers** [comment]
Hmm that didn't work out haha :p

Try to follow these steps:


```
git rebase -i HEAD~4
```

Change the last 3 commits to `f` instead of `p`. Keep the first commit on `p`.

Close the window (and save the file)

```
git push -f
```

**Comment by Amrit01** [comment]
Finally it is in one commit now :)

**Comment by patrickbrouwers** [comment]
Good job, @Amrit01 ! :)

**Pull request merged**
